collections:
  comments:
    output: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "smell"
description: "A linkable reference of code smells and heuristics for better code reviews."
title: "Clean Code: Smells and Heuristics"
